"""Deterministic first worker: produce a real mission brief artifact.

This worker does not claim to perform external research or AI reasoning.
It converts the approved mission title and objective into a traceable Markdown
artifact so Brain's execution path can be verified end to end.
"""

from __future__ import annotations


def build_mission_brief(title: str, objective: str) -> str:
    """Return a non-empty Markdown brief for a mission."""
    clean_title = title.strip()
    clean_objective = objective.strip()
    if not clean_title:
        raise ValueError("Mission title must not be empty.")
    if not clean_objective:
        raise ValueError("Mission objective must not be empty.")

    return (
        f"# Mission Brief: {clean_title}\n\n"
        "## Objective\n\n"
        f"{clean_objective}\n\n"
        "## Execution Status\n\n"
        "This artifact was generated by Brain's deterministic document worker. "
        "It records the mission objective; it does not claim that external research, "
        "third-party API calls, or the objective itself have been completed.\n"
    )
